---
- hosts: localhost
  connection: local
  tasks:
  - name: Create EC2 instance of type t2.micro
    amazon.aws.ec2_instance:
      name: "{{item.instance_name}}"
      instance_type: t2.micro
      region: ap-south-1
      security_group: default
      image_id: "{{item.image}}"
      access_key: "{{aws_access_key}}"
      secret_key: "{{aws_secret_key}}"
      key_name: "Devops-new"
      network: 
        assign_public_ip: true
    loop:
      - { image: "ami-053b12d3152c0cc71", instance_name: "ansible-managed-ubuntu-1" }
      - { image: "ami-053b12d3152c0cc71", instance_name: "ansible-managed-ubuntu-2" }
      - { image: "ami-0fd05997b4dff7aac", instance_name: "ansible-managed-amazonlinux-3" }
  

  
